server:
  port: 8082
spring:
  application:
    name: userspreferences
# build:
#   version: "3.0"
# greeting: "Welcome to the Users Service Default environment"
#   contactDetails:
#     name: "Joe Bloggs - Developer"
#     email: "Joe@tus.ie"
#     onCallSupport:
#       - (086) 12345678 
db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200

