spring:
  application:
    name: userservices
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
  management:
    endpoints:
      web:
        exposure:
          include: 'refresh'
